// Level 2
static void menu_add();
static void menu_delete();
static void menu_search();
static void menu_batch_del();
static void menu_advanced_search();
static void menu_reload();
static void menu_exit();
static void menu_error();
